import Foundation

// Generated from Wikimedia Commons metadata when the catalog photos were
// selected. Each entry backs one bundled PNG; the license requires the
// author + license to be displayed for CC BY / CC BY-SA images, which the
// Photo Credits overlay does for all of them.

struct PhotoCredit: Identifiable {
    let id = UUID()
    let imageName: String
    let label: String
    let author: String
    let license: String
    let sourceURL: String
}

let photoCredits: [PhotoCredit] = [
    PhotoCredit(imageName: "fruit-avocado", label: "Avocado (fruit)", author: "Wilfredor", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=103651060"),
    PhotoCredit(imageName: "fruit-banana", label: "Banana (fruit)", author: "Wilfredor", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=25211373"),
    PhotoCredit(imageName: "fruit-cherimoya", label: "Cherimoya (fruit)", author: "Daderot", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=15704974"),
    PhotoCredit(imageName: "fruit-cranberry", label: "Cranberry (fruit)", author: "Keith Weller, USDA-ARS", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=26979"),
    PhotoCredit(imageName: "fruit-date", label: "Date (fruit)", author: "ORGANIChouse", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=52638431"),
    PhotoCredit(imageName: "fruit-dragon-fruit", label: "Dragon Fruit (fruit)", author: "Miwok from France", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=95036959"),
    PhotoCredit(imageName: "fruit-fig", label: "Fig (fruit)", author: "Garitzko", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=7835084"),
    PhotoCredit(imageName: "fruit-gooseberry", label: "Gooseberry (fruit)", author: "mako from Kangasala, Suomi (Finland)", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=7053593"),
    PhotoCredit(imageName: "fruit-grapefruit", label: "Grapefruit (fruit)", author: "Viswaprabha", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=17193083"),
    PhotoCredit(imageName: "fruit-green-apple", label: "Green Apple (fruit)", author: "Justarandomamerican", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=98004794"),
    PhotoCredit(imageName: "fruit-guava", label: "Guava (fruit)", author: "Unknown", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=329"),
    PhotoCredit(imageName: "fruit-lemon", label: "Lemon (fruit)", author: "ben dalton from leeds, uk", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=30743855"),
    PhotoCredit(imageName: "fruit-lime", label: "Lime (fruit)", author: "Forest and Kim Starr", license: "CC BY 3.0 us", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=71907600"),
    PhotoCredit(imageName: "fruit-lychee", label: "Lychee (fruit)", author: "Peggy Greb, USDA ARS", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=2494177"),
    PhotoCredit(imageName: "fruit-mamey", label: "Mamey (fruit)", author: "Sharon Hahn Darlin", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=103474315"),
    PhotoCredit(imageName: "fruit-mandarin", label: "Mandarin (fruit)", author: "Paolo Neo", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=24894960"),
    PhotoCredit(imageName: "fruit-mango", label: "Mango (fruit)", author: "HaJunkiyada", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=182063887"),
    PhotoCredit(imageName: "fruit-orange", label: "Orange (fruit)", author: "rawpixel.com", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=70676148"),
    PhotoCredit(imageName: "fruit-papaya", label: "Papaya (fruit)", author: "Chic Bee", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=159070213"),
    PhotoCredit(imageName: "fruit-persimmon", label: "Persimmon (fruit)", author: "Rodrigo.Argenton", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=40931057"),
    PhotoCredit(imageName: "fruit-pineapple", label: "Pineapple (fruit)", author: "Wilfredor", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=25211393"),
    PhotoCredit(imageName: "fruit-rhubarb", label: "Rhubarb (fruit)", author: "Andrew from Sheffield, UK", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=4226069"),
    PhotoCredit(imageName: "fruit-sapodilla", label: "Sapodilla (fruit)", author: "Rison Thumboor from Thrissur, India", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=74202290"),
    PhotoCredit(imageName: "fruit-sour-cherry", label: "Sour Cherry (fruit)", author: "MmmCCC", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=19919120"),
    PhotoCredit(imageName: "fruit-soursop", label: "Soursop (fruit)", author: "Iwai-Dialax", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=163580055"),
    PhotoCredit(imageName: "fruit-sweet-grape", label: "Sweet Grape (fruit)", author: "W.carter", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=86223228"),
    PhotoCredit(imageName: "fruit-yuzu", label: "Yuzu (fruit)", author: "Ishizaki Yūshi", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=41732345"),
    PhotoCredit(imageName: "recipe-apple-slaw", label: "Apple Slaw (recipe)", author: "Horacio Cambeiro", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=194084156"),
    PhotoCredit(imageName: "recipe-avocado-toast", label: "Avocado Toast (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=181353089"),
    PhotoCredit(imageName: "recipe-banana-pancakes", label: "Banana Pancakes (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=182844746"),
    PhotoCredit(imageName: "recipe-cherimoya-cream", label: "Cherimoya Cream (recipe)", author: "Slamforeman", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=141403035"),
    PhotoCredit(imageName: "recipe-cherry-pie", label: "Cherry Pie (recipe)", author: "Evan-Amos", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=17217096"),
    PhotoCredit(imageName: "recipe-cranberry-sauce", label: "Cranberry Sauce (recipe)", author: "Karen and Brad Emerson", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=103534413"),
    PhotoCredit(imageName: "recipe-date-shake", label: "Date Shake (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=135665393"),
    PhotoCredit(imageName: "recipe-dragon-bowl", label: "Dragon Bowl (recipe)", author: "Ella Olsson from Stockholm, Sweden", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=83080887"),
    PhotoCredit(imageName: "recipe-fig-toasts", label: "Fig Toasts (recipe)", author: "robyn randolph rawsomerobyn", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=61665760"),
    PhotoCredit(imageName: "recipe-gooseberry-fool", label: "Gooseberry Fool (recipe)", author: "David", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=8693565"),
    PhotoCredit(imageName: "recipe-grape-focaccia", label: "Grape Focaccia (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=164107323"),
    PhotoCredit(imageName: "recipe-grapefruit-brulee", label: "Grapefruit Brulee (recipe)", author: "Ата", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=118794429"),
    PhotoCredit(imageName: "recipe-green-mango-salad", label: "Green Mango Salad (recipe)", author: "lazy fri13th", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=88306779"),
    PhotoCredit(imageName: "recipe-grilled-pineapple", label: "Grilled Pineapple (recipe)", author: "Calgary Reviews from Calgary, Canada", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=45512709"),
    PhotoCredit(imageName: "recipe-guava-paste", label: "Guava Paste (recipe)", author: "Carioca", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=1273696"),
    PhotoCredit(imageName: "recipe-kiwi-salsa", label: "Kiwi Salsa (recipe)", author: "Renee Comet (Photographer)", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=24037561"),
    PhotoCredit(imageName: "recipe-lemon-pasta", label: "Lemon Pasta (recipe)", author: "Luca Nebuloni from Milan, Italy", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=50854351"),
    PhotoCredit(imageName: "recipe-lime-pie", label: "Lime Pie (recipe)", author: "Southernscholar at English Wikipedia", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=16660426"),
    PhotoCredit(imageName: "recipe-lychee-sorbet", label: "Lychee Sorbet (recipe)", author: "Renee Comet (photographer)", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=1635473"),
    PhotoCredit(imageName: "recipe-mamey-batido", label: "Mamey Batido (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=164637906"),
    PhotoCredit(imageName: "recipe-mandarin-cake", label: "Mandarin Cake (recipe)", author: "Ella Olsson from Stockholm, Sweden", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=83080766"),
    PhotoCredit(imageName: "recipe-mango-lassi", label: "Mango Lassi (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=134289602"),
    PhotoCredit(imageName: "recipe-orange-salad", label: "Orange Salad (recipe)", author: "U.S. Department of Agriculture", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=63931880"),
    PhotoCredit(imageName: "recipe-papaya-bowl", label: "Papaya Bowl (recipe)", author: "Sharon Hahn Darlin", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=123048767"),
    PhotoCredit(imageName: "recipe-passion-curd", label: "Passion Curd (recipe)", author: "jules", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=144374028"),
    PhotoCredit(imageName: "recipe-persimmon-salad", label: "Persimmon Salad (recipe)", author: "Paul Lowry", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=179848323"),
    PhotoCredit(imageName: "recipe-pom-molasses", label: "Pom Molasses (recipe)", author: "А. Кабанов", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=16374766"),
    PhotoCredit(imageName: "recipe-rhubarb-compote", label: "Rhubarb Compote (recipe)", author: "Peter O'Connor aka anemoneprojectors", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=101307247"),
    PhotoCredit(imageName: "recipe-sapodilla-shake", label: "Sapodilla Shake (recipe)", author: "Renee Comet (Photographer)", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=24046976"),
    PhotoCredit(imageName: "recipe-soursop-juice", label: "Soursop Juice (recipe)", author: "Xemenendura", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=39538482"),
    PhotoCredit(imageName: "recipe-yuzu-ponzu", label: "Yuzu Ponzu (recipe)", author: "Daderot", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=128561905"),

    // Design-phase images (tamarind/calamansi prototype), sourced during the
    // Claude Design phase. Each was matched pixel-for-pixel against its
    // original on Wikimedia Commons / PICRYL / Needpix before the credit
    // below was recorded.
    PhotoCredit(imageName: "tamarind-bg", label: "Tamarind (fruit)", author: "Pixabay contributor, via Needpix", license: "Public domain (CC0)", sourceURL: "https://www.needpix.com/photo/1444132/tamarind-fruit-asian-fruits-bean-brown-exotic-food-fresh"),
    PhotoCredit(imageName: "fruit-calamansi", label: "Calamansi (fruit)", author: "Obsidian Soul", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=81931708"),
    PhotoCredit(imageName: "fruit-passion-fruit", label: "Passion Fruit (fruit)", author: "THOR", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=40606684"),
    PhotoCredit(imageName: "fruit-green-mango", label: "Green Mango (fruit)", author: "Bruno da Silva Lessa", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=3894429"),
    PhotoCredit(imageName: "fruit-kiwi", label: "Kiwi (fruit)", author: "Luc Viatour", license: "CC BY-SA 2.5", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=3563567"),
    PhotoCredit(imageName: "fruit-pomegranate", label: "Pomegranate (fruit)", author: "Government Press Office (GPO), Israel", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=22807461"),
    PhotoCredit(imageName: "recipe-chutney", label: "Tamarind Chutney (recipe)", author: "Netha Hussain", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=126111481"),
    PhotoCredit(imageName: "recipe-padthai", label: "Pad Thai (recipe)", author: "Pixabay contributor, via PICRYL", license: "Public domain (CC0)", sourceURL: "https://picryl.com/media/pad-thai-hungry-noodles-architecture-buildings-c4225f"),
    PhotoCredit(imageName: "recipe-agua", label: "Agua de Tamarindo (recipe)", author: "ProtoplasmaKid", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=36652119"),
    PhotoCredit(imageName: "recipe-ribs", label: "Glazed Pork Ribs (recipe)", author: "Pixabay contributor, via PICRYL", license: "Public domain (CC0)", sourceURL: "https://picryl.com/media/spare-ribs-grill-bbq-food-drink-1bb87f"),
    PhotoCredit(imageName: "recipe-calamansi-ade", label: "Calamansi-ade (recipe)", author: "punctuated", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=79147457"),
    PhotoCredit(imageName: "recipe-calamansi-bars", label: "Calamansi Bars (recipe)", author: "Kjp001", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Lemon_Bar.jpg"),
    PhotoCredit(imageName: "recipe-calamansi-marinade", label: "Calamansi Marinade (recipe)", author: "Herbertkikoy", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Savory_Lechon_Manok.jpg"),
    PhotoCredit(imageName: "recipe-toyomansi", label: "Toyomansi (recipe)", author: "Obsidian Soul", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Toyo_at_kalamansi_(toyomansi)_with_siling_labuyo_(Philippines)_01.jpg"),

    // Recipe card photography (second Commons batch).
    PhotoCredit(imageName: "recipe-aam-panna", label: "Aam Panna (recipe)", author: "Miansari66", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=39891818"),
    PhotoCredit(imageName: "recipe-apple-crisp", label: "Green Apple Crisp (recipe)", author: "Douglas Perkins", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=38786410"),
    PhotoCredit(imageName: "recipe-apple-waldorf", label: "Crunchy Waldorf Salad (recipe)", author: "Nillerdk", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=4190286"),
    PhotoCredit(imageName: "recipe-applesauce", label: "Spiced Applesauce (recipe)", author: "Jonadab", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=12663925"),
    PhotoCredit(imageName: "recipe-avocado-citrus-salad", label: "Avocado Citrus Salad (recipe)", author: "Karen and Brad Emerson", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=103534625"),
    PhotoCredit(imageName: "recipe-avocado-mousse", label: "Avocado Chocolate Mousse (recipe)", author: "Msmirlie2863 at English Wikipedia", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=25318294"),
    PhotoCredit(imageName: "recipe-banana-bread", label: "Banana Bread (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=146892037"),
    PhotoCredit(imageName: "recipe-banana-nice-cream", label: "Banana Nice Cream (recipe)", author: "Arnold Gatilao from Oakland, CA, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=40530447"),
    PhotoCredit(imageName: "recipe-bananas-caramelized", label: "Caramelized Bananas (recipe)", author: "rulenumberone2", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=90141793"),
    PhotoCredit(imageName: "recipe-candied-orange", label: "Candied Orange Peel (recipe)", author: "hux", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=65590452"),
    PhotoCredit(imageName: "recipe-cherimoya-nice-cream", label: "Cherimoya Nice Cream (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=190685429"),
    PhotoCredit(imageName: "recipe-cherimoya-salad", label: "Cherimoya Citrus Salad (recipe)", author: "Renee Comet (Photographer)", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=24037561"),
    PhotoCredit(imageName: "recipe-cherimoya-smoothie", label: "Cherimoya Smoothie (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=164637906"),
    PhotoCredit(imageName: "recipe-cherry-clafoutis", label: "Sour Cherry Clafoutis (recipe)", author: "frank wouters", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=10367139"),
    PhotoCredit(imageName: "recipe-cherry-compote", label: "Sour Cherry Compote (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=180813487"),
    PhotoCredit(imageName: "recipe-cherry-soda", label: "Sour Cherry Soda (recipe)", author: "Mx. Granger", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=112036632"),
    PhotoCredit(imageName: "recipe-choco-mandarins", label: "Chocolate-Dipped Mandarins (recipe)", author: "Brenda Godinez cravethebenefits", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=61853807"),
    PhotoCredit(imageName: "recipe-cranberry-muffins", label: "Cranberry Orange Muffins (recipe)", author: "Pi.phage", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=4165511"),
    PhotoCredit(imageName: "recipe-cranberry-relish", label: "Raw Cranberry Relish (recipe)", author: "Missvain", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=141313621"),
    PhotoCredit(imageName: "recipe-cranberry-spritzer", label: "Cranberry Lime Spritzer (recipe)", author: "Jez Timms jeztimms", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=61903369"),
    PhotoCredit(imageName: "recipe-date-balls", label: "Date Energy Balls (recipe)", author: "Toa Heftiba heftiba", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=62099881"),
    PhotoCredit(imageName: "recipe-date-porridge", label: "Sticky Date Porridge (recipe)", author: "UserTwoSix", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=103585646"),
    PhotoCredit(imageName: "recipe-dates-stuffed", label: "Stuffed Dates (recipe)", author: "Daderot", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=143701127"),
    PhotoCredit(imageName: "recipe-dragon-chia", label: "Dragon Fruit Chia Pudding (recipe)", author: "Miscellaneous contributor", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=106197215"),
    PhotoCredit(imageName: "recipe-dragon-lemonade", label: "Dragon Fruit Lemonade (recipe)", author: "Personal Creations", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=148028748"),
    PhotoCredit(imageName: "recipe-dragon-salsa", label: "Dragon Fruit Salsa (recipe)", author: "rajucreddy", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=142877287"),
    PhotoCredit(imageName: "recipe-fig-jam", label: "Fig Jam (recipe)", author: "Bran_Muffin_with_Tangelo_Fig_Compote.jpg: Janet Hudson de…", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=17290071"),
    PhotoCredit(imageName: "recipe-fig-salad", label: "Fig & Arugula Salad (recipe)", author: "Daderot", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=143990598"),
    PhotoCredit(imageName: "recipe-figs-roasted", label: "Honey-Roasted Figs (recipe)", author: "Unknown", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=179018789"),
    PhotoCredit(imageName: "recipe-gooseberry-chutney", label: "Gooseberry Chutney (recipe)", author: "Vouliagmeni", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=11825929"),
    PhotoCredit(imageName: "recipe-gooseberry-crumble", label: "Gooseberry Crumble (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=129543661"),
    PhotoCredit(imageName: "recipe-gooseberry-jam", label: "Gooseberry Jam (recipe)", author: "Mx. Granger", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=93655830"),
    PhotoCredit(imageName: "recipe-grape-chicken-salad", label: "Chicken & Grape Salad (recipe)", author: "Thomson200", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=86063670"),
    PhotoCredit(imageName: "recipe-grape-granita", label: "Grape Granita (recipe)", author: "Adriao", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=7250489"),
    PhotoCredit(imageName: "recipe-grapefruit-avocado", label: "Grapefruit & Avocado Salad (recipe)", author: "Daderot", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=148686390"),
    PhotoCredit(imageName: "recipe-grapefruit-marmalade", label: "Grapefruit Marmalade (recipe)", author: "jules", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=22382226"),
    PhotoCredit(imageName: "recipe-grapefruit-sparkler", label: "Grapefruit Rosemary Sparkler (recipe)", author: "Antonio Cavallo", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=12523244"),
    PhotoCredit(imageName: "recipe-grapes-roasted", label: "Roasted Grapes & Ricotta (recipe)", author: "Mihail Verbal", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=178827758"),
    PhotoCredit(imageName: "recipe-green-mango-chutney", label: "Green Mango Chutney (recipe)", author: "Biswarup Ganguly", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=13731169"),
    PhotoCredit(imageName: "recipe-green-mango-slaw", label: "Green Mango Slaw (recipe)", author: "T.Tseng", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=87636523"),
    PhotoCredit(imageName: "recipe-guacamole", label: "Proper Guacamole (recipe)", author: "Jon Sullivan", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=423777"),
    PhotoCredit(imageName: "recipe-guava-agua", label: "Guava Agua Fresca (recipe)", author: "Original uploader was ManekiNeko at en.wikipedia", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=6340598"),
    PhotoCredit(imageName: "recipe-guava-glaze", label: "Guava BBQ Glaze (recipe)", author: "QuickQuokka", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=116124840"),
    PhotoCredit(imageName: "recipe-guava-pastelitos", label: "Guava Pastelitos (recipe)", author: "Horacio Cambeiro", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=187834584"),
    PhotoCredit(imageName: "recipe-kiwi-parfait", label: "Kiwi Chia Parfait (recipe)", author: "Brenda Godinez cravethebenefits", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=61666180"),
    PhotoCredit(imageName: "recipe-kiwi-pavlova", label: "Kiwi Pavlova (recipe)", author: "Hazel Fowler", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=4057307"),
    PhotoCredit(imageName: "recipe-kiwi-smoothie", label: "Kiwi Green Smoothie (recipe)", author: "rawpixel.com", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=122615036"),
    PhotoCredit(imageName: "recipe-lemon-chicken", label: "Lemon-Herb Roast Chicken (recipe)", author: "Missvain", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=81464824"),
    PhotoCredit(imageName: "recipe-lemonade", label: "Whole-Lemon Lemonade (recipe)", author: "Grandmaster Huon", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=142828181"),
    PhotoCredit(imageName: "recipe-lime-rice", label: "Lime Cilantro Rice (recipe)", author: "Missvain", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=157570626"),
    PhotoCredit(imageName: "recipe-limeade", label: "Classic Limeade (recipe)", author: "T.Tseng", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=75545323"),
    PhotoCredit(imageName: "recipe-lychee-iced-tea", label: "Lychee Iced Tea (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=175582832"),
    PhotoCredit(imageName: "recipe-lychee-panna-cotta", label: "Lychee Panna Cotta (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=168780024"),
    PhotoCredit(imageName: "recipe-lychee-salad", label: "Lychee & Mint Salad (recipe)", author: "slgckgc", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=86749391"),
    PhotoCredit(imageName: "recipe-mamey-bowl", label: "Mamey Smoothie Bowl (recipe)", author: "Ben Neale ben_neale", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=62336578"),
    PhotoCredit(imageName: "recipe-mamey-flan", label: "Mamey Flan (recipe)", author: "Obsidian Soul", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=114401551"),
    PhotoCredit(imageName: "recipe-mamey-ice-cream", label: "Mamey Ice Cream (recipe)", author: "Cristóbal Meléndez", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=71287099"),
    PhotoCredit(imageName: "recipe-mandarin-dressing", label: "Mandarin Ginger Dressing (recipe)", author: "Bill Branson (photographer)", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=10532152"),
    PhotoCredit(imageName: "recipe-mandarin-salad", label: "Mandarin Spinach Salad (recipe)", author: "Valereee", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=147448524"),
    PhotoCredit(imageName: "recipe-mango-salsa", label: "Mango Salsa (recipe)", author: "cogdogblog", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=57023408"),
    PhotoCredit(imageName: "recipe-mango-sorbet", label: "Mango Sorbet (recipe)", author: "T.Tseng", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=95623712"),
    PhotoCredit(imageName: "recipe-mango-sticky-rice", label: "Mango Sticky Rice (recipe)", author: "Terence Ong", license: "CC BY 2.5", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=2351767"),
    PhotoCredit(imageName: "recipe-orange-chicken", label: "Crispy Orange Chicken (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=179428367"),
    PhotoCredit(imageName: "recipe-orange-compote", label: "Orange-Cinnamon Compote (recipe)", author: "rajucreddy", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=142877277"),
    PhotoCredit(imageName: "recipe-papaya-batido", label: "Papaya Batido (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=148670067"),
    PhotoCredit(imageName: "recipe-papaya-salad", label: "Green Papaya Salad (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=149397297"),
    PhotoCredit(imageName: "recipe-papaya-sorbet", label: "Papaya-Lime Sorbet (recipe)", author: "Tangopaso", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=18423779"),
    PhotoCredit(imageName: "recipe-passion-mousse", label: "Passion Fruit Mousse (recipe)", author: "Gilberto Santa Rosa", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=5577593"),
    PhotoCredit(imageName: "recipe-passion-tea", label: "Passion Fruit Iced Tea (recipe)", author: "Fumikas Sagisavas", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=152614797"),
    PhotoCredit(imageName: "recipe-passion-vinaigrette", label: "Passion Fruit Vinaigrette (recipe)", author: "Nana Pearls", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=164041032"),
    PhotoCredit(imageName: "recipe-persimmon-bread", label: "Persimmon Spice Bread (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=176951624"),
    PhotoCredit(imageName: "recipe-persimmon-salsa", label: "Persimmon Salsa (recipe)", author: "yellowcloud from Germany", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=24974921"),
    PhotoCredit(imageName: "recipe-persimmon-smoothie", label: "Persimmon Smoothie (recipe)", author: "Shixart1985", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=186342596"),
    PhotoCredit(imageName: "recipe-pineapple-fried-rice", label: "Pineapple Fried Rice (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=169578169"),
    PhotoCredit(imageName: "recipe-pineapple-salsa", label: "Charred Pineapple Salsa (recipe)", author: "Jakeddy", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=173847102"),
    PhotoCredit(imageName: "recipe-pineapple-smoothie", label: "Piña Coconut Smoothie (recipe)", author: "Photographer: Kyle T. Ramirez", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=23103659"),
    PhotoCredit(imageName: "recipe-pom-couscous", label: "Jeweled Couscous (recipe)", author: "Karen and Brad Emerson", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=103534551"),
    PhotoCredit(imageName: "recipe-pom-raita", label: "Pomegranate Raita (recipe)", author: "Miansari66", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=13167566"),
    PhotoCredit(imageName: "recipe-pom-spritzer", label: "Pomegranate Spritzer (recipe)", author: "Miansari66", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=8322927"),
    PhotoCredit(imageName: "recipe-preserved-lemons", label: "Preserved Lemons (recipe)", author: "Miansari66", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=26954503"),
    PhotoCredit(imageName: "recipe-rhubarb-crumble", label: "Rhubarb Crumble (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=185976618"),
    PhotoCredit(imageName: "recipe-rhubarb-roasted", label: "Roasted Rhubarb & Yogurt (recipe)", author: "Slamforeman", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=141403035"),
    PhotoCredit(imageName: "recipe-rhubarb-syrup", label: "Rhubarb Syrup (recipe)", author: "Stewart Butterfield from Vancouver, Canada", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=92252957"),
    PhotoCredit(imageName: "recipe-sapodilla-chaat", label: "Chikoo Chaat Cups (recipe)", author: "Miansari66", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=7914171"),
    PhotoCredit(imageName: "recipe-sapodilla-halwa", label: "Chikoo Halwa (recipe)", author: "Miansari66", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=15827595"),
    PhotoCredit(imageName: "recipe-sapodilla-ice-cream", label: "Chikoo Ice Cream (recipe)", author: "Miansari66", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=15200781"),
    PhotoCredit(imageName: "recipe-shrimp-ceviche", label: "Shrimp Ceviche (recipe)", author: "Jorge G. Mori", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=3749415"),
    PhotoCredit(imageName: "recipe-soursop-punch", label: "Soursop Punch (recipe)", author: "https://www.flickr.com/photos/16989146@N06/", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=39535206"),
    PhotoCredit(imageName: "recipe-soursop-smoothie", label: "Soursop Smoothie (recipe)", author: "Spideog", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=163722841"),
    PhotoCredit(imageName: "recipe-soursop-sorbet", label: "Soursop Sorbet (recipe)", author: "XXMaxusXx", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=76966794"),
    PhotoCredit(imageName: "recipe-yuzu-curd", label: "Yuzu Curd (recipe)", author: "Ella Olsson from Stockholm, Sweden", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=83080761"),
    PhotoCredit(imageName: "recipe-yuzu-tea", label: "Yuzu Honey Tea (recipe)", author: "Ajumeoni", license: "CC0", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=74513789"),
    PhotoCredit(imageName: "recipe-yuzu-vinaigrette", label: "Yuzu Vinaigrette (recipe)", author: "User:逃亡者 (ja:利用者:逃亡者)", license: "Public domain", sourceURL: "https://commons.wikimedia.org/w/index.php?curid=161437537"),
    PhotoCredit(imageName: "fruit-apricot", label: "Apricot (fruit)", author: "Fir0002", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Apricots.jpg"),
    PhotoCredit(imageName: "fruit-blackberry", label: "Blackberry (fruit)", author: "Ivar Leidus", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Blackberries_(Rubus_fruticosus).jpg"),
    PhotoCredit(imageName: "fruit-blood-orange", label: "Blood Orange (fruit)", author: "Rhododendrites", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Blood_orange_slice.jpg"),
    PhotoCredit(imageName: "fruit-coconut", label: "Coconut (fruit)", author: "Chandrika Nair from Cochin, India", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Coconut_(halved)_(3330701660).jpg"),
    PhotoCredit(imageName: "fruit-durian", label: "Durian (fruit)", author: "Kembangraps", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Durian_fruit_opened_PJ_DSC_0802.jpg"),
    PhotoCredit(imageName: "fruit-jackfruit", label: "Jackfruit (fruit)", author: "Asit K. Ghosh Thaumaturgist", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Jackfruit_NS-1_01_Asit.jpg"),
    PhotoCredit(imageName: "fruit-kumquat", label: "Kumquat (fruit)", author: "Ivar Leidus", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Kumquat_from_Spain.jpg"),
    PhotoCredit(imageName: "fruit-peach", label: "Peach (fruit)", author: "Jack Dykinga, USDA", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Autumn_Red_peaches.jpg"),
    PhotoCredit(imageName: "fruit-pear", label: "Pear (fruit)", author: "Rhododendrites", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Four_pears.jpg"),
    PhotoCredit(imageName: "fruit-plum", label: "Plum (fruit)", author: "Fir0002", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Plums.jpg"),
    PhotoCredit(imageName: "fruit-pomelo", label: "Pomelo (fruit)", author: "Ivar Leidus", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Pomelo_fruit.jpg"),
    PhotoCredit(imageName: "fruit-raspberry", label: "Raspberry (fruit)", author: "Ivar Leidus", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Raspberry_-_halved_(Rubus_idaeus).jpg"),
    PhotoCredit(imageName: "fruit-red-currant", label: "Red Currant (fruit)", author: "Ivar Leidus", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Redcurrant_(Ribes_rubrum)_fruits.jpg"),
    PhotoCredit(imageName: "fruit-starfruit", label: "Starfruit (fruit)", author: "SMasters", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Carambola_Starfruit.jpg"),
    PhotoCredit(imageName: "fruit-strawberry", label: "Strawberry (fruit)", author: "W.carter", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Still_life_with_strawberries_in_a_crystal_bowl.jpg"),
    PhotoCredit(imageName: "fruit-watermelon", label: "Watermelon (fruit)", author: "Ralff Nestor Nacor", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Watermelon_slice,_May_2024.jpg"),
    PhotoCredit(imageName: "recipe-apricot-crumble", label: "Apricot Almond Crumble (recipe)", author: "Benoît Prieur", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Po%C3%A9l%C3%A9e_d%27abricot_au_sirop_d%27%C3%A9rable_et_au_romarin_(glace_yaourt_et_crumble_Sp%C3%A9culos).jpg"),
    PhotoCredit(imageName: "recipe-apricot-jam", label: "Apricot Jam (recipe)", author: "Colorado State University Extension", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Fruit_preserve_jars.jpg"),
    PhotoCredit(imageName: "recipe-apricot-tagine", label: "Apricot Chicken Tagine (recipe)", author: "Kimberly Vardeman", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:African_Dinner-01.jpg"),
    PhotoCredit(imageName: "recipe-apricots-grilled", label: "Grilled Apricots & Honey (recipe)", author: "Aerous", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Fruit_skewers.jpg"),
    PhotoCredit(imageName: "recipe-blackberry-cobbler", label: "Blackberry Cobbler (recipe)", author: "No machine-readable author provided. Infratec~commonswiki assumed (based on copy", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Apple_cobbler.jpg"),
    PhotoCredit(imageName: "recipe-blackberry-jam", label: "Blackberry Jam (recipe)", author: "Saintfevrier", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Rubus_fruticosus_preserves.JPG"),
    PhotoCredit(imageName: "recipe-blackberry-sauce", label: "Blackberry Pan Sauce (recipe)", author: "Unknown", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Greek_yoghurt_panna_cotta_in_blackberry_sauce.jpg"),
    PhotoCredit(imageName: "recipe-blackberry-smoothie", label: "Blackberry Smoothie (recipe)", author: "Personal Creations", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Kid_friendly_green_smoothie_in_a_personalized_glass_with_spinach,_Greek_yogurt,_frozen_blueberries,_blackberries_and_strawberries_and_berries,_banana_in_a_glass_bowl_on_a_wood_table_(16225943125).jpg"),
    PhotoCredit(imageName: "recipe-blood-orange-cake", label: "Blood Orange Olive Oil Cake (recipe)", author: "little blue hen", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Blood_orange_upside-down_cake,_March_2010.jpg"),
    PhotoCredit(imageName: "recipe-blood-orange-marmalade", label: "Blood Orange Marmalade (recipe)", author: "Kate", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Blood_orange_marmalade,_January_2011.jpg"),
    PhotoCredit(imageName: "recipe-blood-orange-salad", label: "Blood Orange & Fennel Salad (recipe)", author: "Oliviero Scalia", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Sicilian_Blood_Orange_Salad.jpg"),
    PhotoCredit(imageName: "recipe-blood-orangeade", label: "Blood Orangeade (recipe)", author: "Jengod", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Blood_orange_citrus_juicing_simple_machine_manual_lever_01.jpg"),
    PhotoCredit(imageName: "recipe-coconut-chutney", label: "Coconut Chutney (recipe)", author: "Ravi Dwivedi", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Butter_Dosa_served_with_coconut_chutney_and_sambhar.jpg"),
    PhotoCredit(imageName: "recipe-coconut-macaroons", label: "Coconut Macaroons (recipe)", author: "Roozitaa", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Shirini_Nargili_Khanegi.jpg"),
    PhotoCredit(imageName: "recipe-coconut-rice", label: "Coconut Rice (recipe)", author: "Andy Li", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Coconut_Rice_-_Easythaiger_2026-04-21.jpg"),
    PhotoCredit(imageName: "recipe-durian-ice-cream", label: "Durian Ice Cream (recipe)", author: "SpartacksCompatriot", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Durian_ice_cream_from_Pulau_Karam.JPG"),
    PhotoCredit(imageName: "recipe-durian-pancakes", label: "Durian Crepe Pillows (recipe)", author: "ZAC", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Durian_Pancake.jpg"),
    PhotoCredit(imageName: "recipe-durian-smoothie", label: "Durian Smoothie (recipe)", author: "Gunawan Kartapranata", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Es_Durian.jpg"),
    PhotoCredit(imageName: "recipe-durian-sticky-rice", label: "Durian Sticky Rice (recipe)", author: "Taman Renyah", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Ketan_saus_durian.jpg"),
    PhotoCredit(imageName: "recipe-jackfruit-chips", label: "Baked Jackfruit Chips (recipe)", author: "Vis M", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Jackfruit_chips_Kerala_02.jpg"),
    PhotoCredit(imageName: "recipe-jackfruit-curry", label: "Jackfruit Curry (recipe)", author: "Vis M", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Jackfruit_curry_2023.jpg"),
    PhotoCredit(imageName: "recipe-jackfruit-smoothie", label: "Ripe Jackfruit Smoothie (recipe)", author: "Dr. Chinchu. C", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Jackfruit_Seed_Shake_Kerala_20190414_220040.jpg"),
    PhotoCredit(imageName: "recipe-jackfruit-tacos", label: "Jackfruit Carnitas Tacos (recipe)", author: "Mercy For Animals MFA from Los Angeles, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Vegan_Tacos_(5654701543).jpg"),
    PhotoCredit(imageName: "recipe-kumquat-marmalade", label: "Kumquat Marmalade (recipe)", author: "Leslie Seaton from Seattle, WA, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Limequat_marmalade_(8449071197).jpg"),
    PhotoCredit(imageName: "recipe-kumquat-salad", label: "Kumquat & Avocado Salad (recipe)", author: "Mervat Salman", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Fresh_Fruit_Salad.jpg"),
    PhotoCredit(imageName: "recipe-kumquat-spritzer", label: "Kumquat Ginger Spritzer (recipe)", author: "Missvain", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Blood_Orange_Spritz_at_Taub_Family_Outpost_in_Sonoma_-_Sarah_Stierch.jpg"),
    PhotoCredit(imageName: "recipe-kumquats-candied", label: "Candied Kumquats (recipe)", author: "Fumikas Sagisavas", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Candied_kumquats.jpg"),
    PhotoCredit(imageName: "recipe-peach-cobbler", label: "Peach Cobbler (recipe)", author: "NumismaticLinguist", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Fresh_Peach_Cobbler.jpg"),
    PhotoCredit(imageName: "recipe-peach-iced-tea", label: "Peach Iced Tea (recipe)", author: "Baoothersks", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Peach_iced_tea_with_orange_slices.jpg"),
    PhotoCredit(imageName: "recipe-peach-salsa", label: "Peach Salsa (recipe)", author: "karol m from arizona, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Sena_sampler.jpg"),
    PhotoCredit(imageName: "recipe-peaches-grilled", label: "Grilled Peaches & Burrata (recipe)", author: "Tony Webster from Minneapolis, Minnesota, United States", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Grilled_Peach_at_Minnesota_State_Fair_(48659750766).jpg"),
    PhotoCredit(imageName: "recipe-pear-butter", label: "Slow Pear Butter (recipe)", author: "Pitschotterli", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Birno_Birnenhonig.jpg"),
    PhotoCredit(imageName: "recipe-pear-crumble", label: "Pear Ginger Crumble (recipe)", author: "Neil Conway from Oakland, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Blackberry_Pear_Crumble_(4747800717).jpg"),
    PhotoCredit(imageName: "recipe-pear-salad", label: "Pear & Blue Cheese Salad (recipe)", author: "Ruth Hartnup from Vancouver, Canada", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Pear_and_blue_cheese_salad_at_Caf%C3%A9_Divine_(14415352734).jpg"),
    PhotoCredit(imageName: "recipe-pears-poached", label: "Spice-Poached Pears (recipe)", author: "Infrogmation of New Orleans", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Poached_Pears_in_bowl.jpg"),
    PhotoCredit(imageName: "recipe-pina-colada", label: "Virgin Piña Colada (recipe)", author: "User Barmix on de.wikipedia", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Pi%C3%B1a_Colada.jpg"),
    PhotoCredit(imageName: "recipe-plum-cake", label: "German Plum Cake (recipe)", author: "Frank Vincentz", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Plum_cake2_ies.jpg"),
    PhotoCredit(imageName: "recipe-plum-galette", label: "Plum Galette (recipe)", author: "WhatamIdoing", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Plum_tart_before_baking.png"),
    PhotoCredit(imageName: "recipe-plum-sauce", label: "Chinese Plum Sauce (recipe)", author: "Badagnani", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Plumsauce.jpg"),
    PhotoCredit(imageName: "recipe-plums-roasted", label: "Vanilla Roasted Plums (recipe)", author: "Xocolatl (talk) 10:57, 29 August 2021 (UTC)", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:AIMG_8100_(2)_Topfenkn%C3%B6del_mit_Zwetschgenr%C3%B6ster.JPG"),
    PhotoCredit(imageName: "recipe-pomelo-chili-salt", label: "Pomelo with Chili Salt (recipe)", author: "HaumeaOrbit", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Pomelo_with_rind_removed_and_segments.jpg"),
    PhotoCredit(imageName: "recipe-pomelo-salad", label: "Yam Som O (Pomelo Salad) (recipe)", author: "แอนเดอร์สัน", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Yam_Som_O,_Thai_Pomelo_Salad_3.jpg"),
    PhotoCredit(imageName: "recipe-pomelo-sorbet", label: "Pomelo Sorbet (recipe)", author: "J from Seattle, USA", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Capitol_Hill_food_and_drink_-_jewelled_rice_pudding_with_citrus_sorbet_(8445080565).jpg"),
    PhotoCredit(imageName: "recipe-pomelo-tea", label: "Pomelo Honey Tea (recipe)", author: "Drew Lietzow", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Korean_yuja_tea.jpg"),
    PhotoCredit(imageName: "recipe-raspberry-chia-jam", label: "Raspberry Chia Jam (recipe)", author: "Evan Swigart from Chicago, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Homemade_White_Bread_with_Strawberry_Jam.jpg"),
    PhotoCredit(imageName: "recipe-raspberry-coulis", label: "Raspberry Coulis (recipe)", author: "Siobhan Leachman", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Pavlova_with_strawberry_and_raspberry_coulis.jpg"),
    PhotoCredit(imageName: "recipe-raspberry-fool", label: "Raspberry Fool (recipe)", author: "David", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Raspberry_fool.jpg"),
    PhotoCredit(imageName: "recipe-raspberry-muffins", label: "Raspberry Muffins (recipe)", author: "Andy / Andrew Fogg from near Cambridge, UK", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Raspberry_muffins_(3244692392).jpg"),
    PhotoCredit(imageName: "recipe-redcurrant-cake", label: "Red Currant Meringue Cake (recipe)", author: "Migle", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Meringue_cake_with_redcurrant_curd_filling_(7801333926).jpg"),
    PhotoCredit(imageName: "recipe-redcurrant-cordial", label: "Red Currant Cordial (recipe)", author: "VdF", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Grapefruit_Johannisbeere.jpg"),
    PhotoCredit(imageName: "recipe-redcurrant-jelly", label: "Red Currant Jelly (recipe)", author: "Amanda Slater from Coventry, West Midlands, UK", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Redcurrant_jelly_(2699068744).jpg"),
    PhotoCredit(imageName: "recipe-redcurrant-sauce", label: "Red Currant Sauce (recipe)", author: "Daniel Sexton", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Duck_confit_crepes_with_Cumberland_sauce.jpg"),
    PhotoCredit(imageName: "recipe-starfruit-candied", label: "Candied Starfruit Stars (recipe)", author: "Esby", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Caramboles_s%C3%A9ch%C3%A9s_-_Japan_Expo_Sud_2013_-_P1560004.JPG"),
    PhotoCredit(imageName: "recipe-starfruit-juice", label: "Starfruit Cooler (recipe)", author: "User:Marcushsu", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:CHENGDU_Starfruit_Juice_Shop.JPG"),
    PhotoCredit(imageName: "recipe-starfruit-salad", label: "Starfruit & Herb Salad (recipe)", author: "Vegan Feast Catering", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Thai_Starfruit_Salad_(3658500583).jpg"),
    PhotoCredit(imageName: "recipe-starfruit-salsa", label: "Starfruit Salsa (recipe)", author: "Maggie from Palm Springs, United States", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Mango_salsa.jpg"),
    PhotoCredit(imageName: "recipe-strawberries-cream", label: "Strawberries & Cream (recipe)", author: "HaJunkiyada", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Strawberries_with_Whipped_Cream.jpg"),
    PhotoCredit(imageName: "recipe-strawberry-jam", label: "Strawberry Jam (recipe)", author: "Hughespr", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Exploding_Strawberry_Jar.JPG"),
    PhotoCredit(imageName: "recipe-strawberry-lemonade", label: "Strawberry Lemonade (recipe)", author: "Fumikas Sagisavas", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Starbucks_refreshers_strawberry_acal_lemonade.jpg"),
    PhotoCredit(imageName: "recipe-strawberry-shortcake", label: "Strawberry Shortcake (recipe)", author: "Shisma", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Shortcake_slice.jpg"),
    PhotoCredit(imageName: "recipe-watermelon-agua", label: "Watermelon Agua Fresca (recipe)", author: "Gzzz", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Aguas_frescas_Juchit%C3%A1n_de_Zaragoza_(1).jpg"),
    PhotoCredit(imageName: "recipe-watermelon-feta", label: "Watermelon Feta Salad (recipe)", author: "Shoshanah", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Watermelon_%26_Feta_Salad.jpg"),
    PhotoCredit(imageName: "recipe-watermelon-gazpacho", label: "Watermelon Gazpacho (recipe)", author: "https://www.flickr.com/photos/vxla/", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Avocado_Gazpacho_at_Toro_Salao.jpg"),
    PhotoCredit(imageName: "recipe-watermelon-granita", label: "Watermelon Granita (recipe)", author: "Nancy Vanatta", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Watermelon_granita_(D4113-1)_by_Nancy_Vanatta.jpg")
]
